# Mode of comparison:
# Mode 1: Detailed column comparison
# Mode 2: Record count comparison
MODE=1

# Output directory or path prefix for results
PATH_STATISTICS_FILE=./result/

# Batch size for DB pagination queries
BATCH_SIZE=1000
